language:
  python
python:
 - "3.9"
install:
 - pip install -U pip
 - pip install -r requirements.txt
 - pip install coverage
 - pip install codecov
script:
  - coverage run -m pytest -q test/
after_success:
  - bash <(curl -s https://codecov.io/bash)
